//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemestrTwo
    {
        public int idVisit { get; set; }
        public int idGroup { get; set; }
        public string Name { get; set; }
        public Nullable<int> Jan1 { get; set; }
        public Nullable<int> Jan2 { get; set; }
        public Nullable<int> Jan3 { get; set; }
        public Nullable<int> Jan4 { get; set; }
        public Nullable<int> Jan5 { get; set; }
        public Nullable<int> Jan6 { get; set; }
        public Nullable<int> Jan7 { get; set; }
        public Nullable<int> Jan8 { get; set; }
        public Nullable<int> Jan9 { get; set; }
        public Nullable<int> Jan10 { get; set; }
        public Nullable<int> Jan11 { get; set; }
        public Nullable<int> Jan12 { get; set; }
        public Nullable<int> Jan13 { get; set; }
        public Nullable<int> Jan14 { get; set; }
        public Nullable<int> Jan15 { get; set; }
        public Nullable<int> Jan16 { get; set; }
        public Nullable<int> Jan17 { get; set; }
        public Nullable<int> Jan18 { get; set; }
        public Nullable<int> Jan19 { get; set; }
        public Nullable<int> Jan20 { get; set; }
        public Nullable<int> Jan21 { get; set; }
        public Nullable<int> Jan22 { get; set; }
        public Nullable<int> Jan23 { get; set; }
        public Nullable<int> Jan24 { get; set; }
        public Nullable<int> Jan25 { get; set; }
        public Nullable<int> Jan26 { get; set; }
        public Nullable<int> Jan27 { get; set; }
        public Nullable<int> Jan28 { get; set; }
        public Nullable<int> Jan29 { get; set; }
        public Nullable<int> Jan30 { get; set; }
        public Nullable<int> Jan31 { get; set; }
        public Nullable<int> Feb1 { get; set; }
        public Nullable<int> Feb2 { get; set; }
        public Nullable<int> Feb3 { get; set; }
        public Nullable<int> Feb4 { get; set; }
        public Nullable<int> Feb5 { get; set; }
        public Nullable<int> Feb6 { get; set; }
        public Nullable<int> Feb7 { get; set; }
        public Nullable<int> Feb8 { get; set; }
        public Nullable<int> Feb9 { get; set; }
        public Nullable<int> Feb10 { get; set; }
        public Nullable<int> Feb11 { get; set; }
        public Nullable<int> Feb12 { get; set; }
        public Nullable<int> Feb13 { get; set; }
        public Nullable<int> Feb14 { get; set; }
        public Nullable<int> Feb15 { get; set; }
        public Nullable<int> Feb16 { get; set; }
        public Nullable<int> Feb17 { get; set; }
        public Nullable<int> Feb18 { get; set; }
        public Nullable<int> Feb19 { get; set; }
        public Nullable<int> Feb20 { get; set; }
        public Nullable<int> Feb22 { get; set; }
        public Nullable<int> Feb23 { get; set; }
        public Nullable<int> Feb24 { get; set; }
        public Nullable<int> Feb25 { get; set; }
        public Nullable<int> Feb26 { get; set; }
        public Nullable<int> Feb27 { get; set; }
        public Nullable<int> Feb28 { get; set; }
        public Nullable<int> Feb29 { get; set; }
        public string Mar1 { get; set; }
        public string Mar2 { get; set; }
        public string Mar3 { get; set; }
        public string Mar4 { get; set; }
        public string Mar5 { get; set; }
        public string Mar6 { get; set; }
        public string Mar7 { get; set; }
        public string Mar8 { get; set; }
        public string Mar9 { get; set; }
        public string Mar10 { get; set; }
        public string Mar11 { get; set; }
        public string Mar12 { get; set; }
        public string Mar13 { get; set; }
        public string Mar14 { get; set; }
        public string Mar15 { get; set; }
        public string Mar16 { get; set; }
        public string Mar17 { get; set; }
        public string Mar18 { get; set; }
        public string Mar19 { get; set; }
        public string Mar20 { get; set; }
        public string Mar21 { get; set; }
        public string Mar22 { get; set; }
        public string Mar23 { get; set; }
        public string Mar24 { get; set; }
        public string Mar25 { get; set; }
        public string Mar26 { get; set; }
        public string Mar27 { get; set; }
        public string Mar28 { get; set; }
        public string Mar29 { get; set; }
        public string Mar30 { get; set; }
        public string Mar31 { get; set; }
        public string Apr1 { get; set; }
        public string Apr2 { get; set; }
        public string Apr3 { get; set; }
        public string Apr4 { get; set; }
        public string Apr5 { get; set; }
        public string Apr6 { get; set; }
        public string Apr7 { get; set; }
        public string Apr8 { get; set; }
        public string Apr9 { get; set; }
        public string Apr10 { get; set; }
        public string Apr11 { get; set; }
        public string Apr12 { get; set; }
        public string Apr13 { get; set; }
        public string Apr14 { get; set; }
        public string Apr15 { get; set; }
        public string Apr16 { get; set; }
        public string Apr17 { get; set; }
        public string Apr18 { get; set; }
        public string Apr19 { get; set; }
        public string Apr20 { get; set; }
        public string Apr21 { get; set; }
        public string Apr22 { get; set; }
        public string Apr23 { get; set; }
        public string Apr24 { get; set; }
        public string Apr25 { get; set; }
        public string Apr26 { get; set; }
        public string Apr27 { get; set; }
        public string Apr28 { get; set; }
        public string Apr29 { get; set; }
        public string Apr30 { get; set; }
        public string May1 { get; set; }
        public string May2 { get; set; }
        public string May3 { get; set; }
        public string May4 { get; set; }
        public string May5 { get; set; }
        public string May6 { get; set; }
        public string May7 { get; set; }
        public string May8 { get; set; }
        public string May9 { get; set; }
        public string May10 { get; set; }
        public string May11 { get; set; }
        public string May12 { get; set; }
        public string May13 { get; set; }
        public string May14 { get; set; }
        public string May15 { get; set; }
        public string May16 { get; set; }
        public string May17 { get; set; }
        public string May18 { get; set; }
        public string May19 { get; set; }
        public string May20 { get; set; }
        public string May21 { get; set; }
        public string May22 { get; set; }
        public string May23 { get; set; }
        public string May24 { get; set; }
        public string May25 { get; set; }
        public string May26 { get; set; }
        public string May27 { get; set; }
        public string May28 { get; set; }
        public string May29 { get; set; }
        public string May30 { get; set; }
        public string May31 { get; set; }
        public string Jun1 { get; set; }
        public string Jun2 { get; set; }
        public string Jun3 { get; set; }
        public string Jun4 { get; set; }
        public string Jun5 { get; set; }
        public string Jun6 { get; set; }
        public string Jun7 { get; set; }
        public string Jun9 { get; set; }
        public string Jun10 { get; set; }
        public string Jun11 { get; set; }
        public string Jun12 { get; set; }
        public string Jun13 { get; set; }
        public string Jun14 { get; set; }
        public string Jun15 { get; set; }
        public string Jun16 { get; set; }
        public string Jun17 { get; set; }
        public string Jun18 { get; set; }
        public string Jun19 { get; set; }
        public string Jun20 { get; set; }
        public string Jun21 { get; set; }
        public string Jun22 { get; set; }
        public string Jun23 { get; set; }
        public string Jun24 { get; set; }
        public string Jun25 { get; set; }
        public string Jun26 { get; set; }
        public string Jun27 { get; set; }
        public string Jun28 { get; set; }
        public string Jun29 { get; set; }
        public string Jun30 { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
