//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemestrOne
    {
        public int idVisit { get; set; }
        public int idGroup { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sept1 { get; set; }
        public Nullable<int> Sept2 { get; set; }
        public Nullable<int> Sept3 { get; set; }
        public Nullable<int> Sept4 { get; set; }
        public Nullable<int> Sept5 { get; set; }
        public Nullable<int> Sept6 { get; set; }
        public Nullable<int> Sept7 { get; set; }
        public Nullable<int> Sept8 { get; set; }
        public Nullable<int> Sept9 { get; set; }
        public Nullable<int> Sept10 { get; set; }
        public Nullable<int> Sept11 { get; set; }
        public Nullable<int> Sept12 { get; set; }
        public Nullable<int> Sept13 { get; set; }
        public Nullable<int> Sept14 { get; set; }
        public Nullable<int> Sept15 { get; set; }
        public Nullable<int> Sept16 { get; set; }
        public Nullable<int> Sept17 { get; set; }
        public Nullable<int> Sept18 { get; set; }
        public Nullable<int> Sept19 { get; set; }
        public Nullable<int> Sept20 { get; set; }
        public Nullable<int> Sept21 { get; set; }
        public Nullable<int> Sept22 { get; set; }
        public Nullable<int> Sept23 { get; set; }
        public Nullable<int> Sept24 { get; set; }
        public Nullable<int> Sept25 { get; set; }
        public Nullable<int> Sept26 { get; set; }
        public Nullable<int> Sept27 { get; set; }
        public Nullable<int> Sept28 { get; set; }
        public Nullable<int> Sept29 { get; set; }
        public Nullable<int> Sept30 { get; set; }
        public Nullable<int> Oct1 { get; set; }
        public Nullable<int> Oct2 { get; set; }
        public Nullable<int> Oct3 { get; set; }
        public Nullable<int> Oct4 { get; set; }
        public Nullable<int> Oct5 { get; set; }
        public Nullable<int> Oct6 { get; set; }
        public Nullable<int> Oct7 { get; set; }
        public Nullable<int> Oct8 { get; set; }
        public Nullable<int> Oct9 { get; set; }
        public Nullable<int> Oct10 { get; set; }
        public Nullable<int> Oct11 { get; set; }
        public Nullable<int> Oct12 { get; set; }
        public Nullable<int> Oct13 { get; set; }
        public Nullable<int> Oct14 { get; set; }
        public Nullable<int> Oct15 { get; set; }
        public Nullable<int> Oct16 { get; set; }
        public Nullable<int> Oct17 { get; set; }
        public Nullable<int> Oct18 { get; set; }
        public Nullable<int> Oct19 { get; set; }
        public Nullable<int> Oct20 { get; set; }
        public Nullable<int> Oct21 { get; set; }
        public Nullable<int> Oct22 { get; set; }
        public Nullable<int> Oct23 { get; set; }
        public Nullable<int> Oct24 { get; set; }
        public Nullable<int> Oct25 { get; set; }
        public Nullable<int> Oct26 { get; set; }
        public Nullable<int> Oct27 { get; set; }
        public Nullable<int> Oct28 { get; set; }
        public Nullable<int> Oct29 { get; set; }
        public Nullable<int> Oct30 { get; set; }
        public Nullable<int> Oct31 { get; set; }
        public Nullable<int> Nov1 { get; set; }
        public Nullable<int> Nov2 { get; set; }
        public Nullable<int> Nov3 { get; set; }
        public Nullable<int> Nov4 { get; set; }
        public Nullable<int> Nov5 { get; set; }
        public Nullable<int> Nov6 { get; set; }
        public Nullable<int> Nov7 { get; set; }
        public Nullable<int> Nov8 { get; set; }
        public Nullable<int> Nov9 { get; set; }
        public Nullable<int> Nov10 { get; set; }
        public Nullable<int> Nov11 { get; set; }
        public Nullable<int> Nov12 { get; set; }
        public Nullable<int> Nov13 { get; set; }
        public Nullable<int> Nov14 { get; set; }
        public Nullable<int> Nov15 { get; set; }
        public Nullable<int> Nov16 { get; set; }
        public Nullable<int> Nov17 { get; set; }
        public Nullable<int> Nov18 { get; set; }
        public Nullable<int> Nov19 { get; set; }
        public Nullable<int> Nov20 { get; set; }
        public Nullable<int> Nov21 { get; set; }
        public Nullable<int> Nov22 { get; set; }
        public Nullable<int> Nov23 { get; set; }
        public Nullable<int> Nov24 { get; set; }
        public Nullable<int> Nov25 { get; set; }
        public Nullable<int> Nov26 { get; set; }
        public Nullable<int> Nov27 { get; set; }
        public Nullable<int> Nov28 { get; set; }
        public Nullable<int> Nov29 { get; set; }
        public Nullable<int> Nov30 { get; set; }
        public Nullable<int> Dec1 { get; set; }
        public Nullable<int> Dec2 { get; set; }
        public Nullable<int> Dec3 { get; set; }
        public Nullable<int> Dec4 { get; set; }
        public Nullable<int> Dec5 { get; set; }
        public Nullable<int> Dec6 { get; set; }
        public Nullable<int> Dec7 { get; set; }
        public Nullable<int> Dec8 { get; set; }
        public Nullable<int> Dec9 { get; set; }
        public Nullable<int> Dec10 { get; set; }
        public Nullable<int> Dec11 { get; set; }
        public Nullable<int> Dec12 { get; set; }
        public Nullable<int> Dec13 { get; set; }
        public Nullable<int> Dec14 { get; set; }
        public Nullable<int> Dec15 { get; set; }
        public Nullable<int> Dec16 { get; set; }
        public Nullable<int> Dec17 { get; set; }
        public Nullable<int> Dec18 { get; set; }
        public Nullable<int> Dec19 { get; set; }
        public Nullable<int> Dec20 { get; set; }
        public Nullable<int> Dec21 { get; set; }
        public Nullable<int> Dec22 { get; set; }
        public Nullable<int> Dec23 { get; set; }
        public Nullable<int> Dec24 { get; set; }
        public Nullable<int> Dec25 { get; set; }
        public Nullable<int> Dec26 { get; set; }
        public Nullable<int> Dec27 { get; set; }
        public Nullable<int> Dec28 { get; set; }
        public Nullable<int> Dec29 { get; set; }
        public Nullable<int> Dec30 { get; set; }
        public Nullable<int> Dec31 { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
